# Generated by Django 5.1.3 on 2026-02-15 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificaterequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("HOD Approved", "HOD Approved"),
                    ("Rejected", "Rejected"),
                    ("Ready", "Ready"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="certificaterequest",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificate_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
