# Generated by Django 5.1.3 on 2026-02-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests_app", "0002_alter_certificaterequest_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificaterequest",
            name="staff_remarks",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="certificaterequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("HOD Approved", "HOD Approved"),
                    ("Rejected", "Rejected"),
                    ("Completed", "Completed"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CS", "Computer Science"),
                    ("ECC", "Ecconomics"),
                    ("PHY", "Physics"),
                    ("ENG", "English"),
                    ("MAL", "Malayalam"),
                    ("CHEM", "Chemistry"),
                    ("BOT", "Botany"),
                    ("ZOO", "Zoology"),
                    ("MATH", "Mathematics"),
                ],
                max_length=20,
            ),
        ),
    ]
