# Generated by Django 5.1.3 on 2026-02-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests_app", "0003_certificaterequest_staff_remarks_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CS", "Computer Science"),
                    ("ECO", "Economics"),
                    ("PHY", "Physics"),
                    ("ENG", "English"),
                    ("MAL", "Malayalam"),
                    ("CHEM", "Chemistry"),
                    ("BOT", "Botany"),
                    ("ZOO", "Zoology"),
                    ("MATH", "Mathematics"),
                ],
                max_length=20,
            ),
        ),
    ]
