# Generated by Django 5.1.3 on 2026-03-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests_app", "0004_alter_user_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificaterequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("HOD Approved", "HOD Approved"),
                    ("Principal Approved", "Principal Approved"),
                    ("Rejected", "Rejected"),
                    ("Completed", "Completed"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("hod", "HOD"),
                    ("principal", "Principal"),
                    ("staff", "Office Staff"),
                ],
                default="student",
                max_length=10,
            ),
        ),
    ]
