# Generated by Django 5.2.9 on 2026-05-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0005_alter_certificaterequest_status_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequest',
            name='principal_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='hod_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='staff_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('HOD Approved', 'HOD Approved'), ('Principal Approved', 'Principal Approved'), ('Rejected by HOD', 'Rejected by HOD'), ('Rejected by Principal', 'Rejected by Principal'), ('Completed', 'Completed')], default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('CS', 'Computer Science'), ('ECO', 'Economics'), ('PHY', 'Physics'), ('ENG', 'English'), ('MAL', 'Malayalam'), ('CHEM', 'Chemistry'), ('BOT', 'Botany'), ('ZOO', 'Zoology'), ('MATH', 'Mathematics')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('hod', 'HOD'), ('principal', 'Principal'), ('staff', 'Office Staff')], default='student', max_length=20),
        ),
    ]
