# Generated by Django 5.2.9 on 2026-05-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0006_certificaterequest_principal_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
