# Generated by Django 5.2.9 on 2026-05-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0009_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequest',
            name='year_of_study',
            field=models.CharField(choices=[('I Year', 'I Year'), ('II Year', 'II Year'), ('III Year', 'III Year'), ('IV Year', 'IV Year'), ('I Year PG', 'I Year PG'), ('II Year PG', 'II Year PG')], default='III Year', max_length=20),
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='purpose',
            field=models.TextField(blank=True),
        ),
    ]
