"""
Django settings for certificate_system project.

Generated by 'django-admin startproject' using Django 5.2.9.
"""

from pathlib import Path
from dotenv import load_dotenv
import os
import dj_database_url

# Load environment variables
load_dotenv()

# Base directory
BASE_DIR = Path(__file__).resolve().parent.parent


# =========================================================
# SECURITY SETTINGS
# =========================================================

SECRET_KEY = os.getenv(
    'SECRET_KEY',
    'django-insecure-change-this-in-production'
)

DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [
    '.onrender.com',
    'projectccrs2025.pythonanywhere.com',
    'localhost',
    '127.0.0.1',
]

CSRF_TRUSTED_ORIGINS = [
    'https://*.onrender.com',
    'https://projectccrs2025.pythonanywhere.com',
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# =========================================================
# APPLICATIONS
# =========================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    # Custom app
    'requests_app',
]


# =========================================================
# MIDDLEWARE
# =========================================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# =========================================================
# URLS & WSGI
# =========================================================

ROOT_URLCONF = 'certificate_system.urls'

WSGI_APPLICATION = 'certificate_system.wsgi.application'


# =========================================================
# TEMPLATES
# =========================================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [
            BASE_DIR / 'templates',
        ],

        'APP_DIRS': True,

        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# =========================================================
# DATABASE
# =========================================================

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        ssl_require=False,
    )
}


# =========================================================
# PASSWORD VALIDATION
# =========================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# =========================================================
# INTERNATIONALIZATION
# =========================================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# =========================================================
# STATIC FILES
# =========================================================

STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
] if (BASE_DIR / 'static').exists() else []

STATICFILES_STORAGE = (
    'whitenoise.storage.CompressedManifestStaticFilesStorage'
)


# =========================================================
# MEDIA FILES
# =========================================================

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# =========================================================
# CUSTOM USER MODEL
# =========================================================

AUTH_USER_MODEL = 'requests_app.User'


# =========================================================
# LOGIN / LOGOUT
# =========================================================

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# =========================================================
# EMAIL CONFIGURATION — DUAL PROVIDER WITH FALLBACK
# =========================================================

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_TIMEOUT = 30

# Primary provider: 'sendgrid' or 'gmail'
EMAIL_PROVIDER = os.getenv('EMAIL_PROVIDER', 'gmail')

# --- SendGrid Config ---
SENDGRID_HOST = 'smtp.sendgrid.net'
SENDGRID_PORT = 587
SENDGRID_USER = 'apikey'
SENDGRID_PASSWORD = os.getenv('SENDGRID_API_KEY', '')
SENDGRID_FROM = os.getenv('SENDGRID_FROM_EMAIL', '')

# --- Gmail Config ---
GMAIL_HOST = 'smtp.gmail.com'
GMAIL_PORT = 587
GMAIL_USER = os.getenv('GMAIL_USER', '')
GMAIL_PASSWORD = os.getenv('GMAIL_PASSWORD', '')
GMAIL_FROM = os.getenv('GMAIL_FROM_EMAIL', '')

# --- Set the active provider ---
if EMAIL_PROVIDER == 'sendgrid':
    EMAIL_HOST = SENDGRID_HOST
    EMAIL_PORT = SENDGRID_PORT
    EMAIL_USE_TLS = True
    EMAIL_USE_SSL = False
    EMAIL_HOST_USER = SENDGRID_USER
    EMAIL_HOST_PASSWORD = SENDGRID_PASSWORD
    DEFAULT_FROM_EMAIL = SENDGRID_FROM

else:
    EMAIL_HOST = GMAIL_HOST
    EMAIL_PORT = GMAIL_PORT
    EMAIL_USE_TLS = True
    EMAIL_USE_SSL = False
    EMAIL_HOST_USER = GMAIL_USER
    EMAIL_HOST_PASSWORD = GMAIL_PASSWORD
    DEFAULT_FROM_EMAIL = GMAIL_FROM


# =========================================================
# DJANGO SITES FRAMEWORK
# =========================================================

SITE_ID = 1


# =========================================================
# DEFAULT PRIMARY KEY
# =========================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'